name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << 'EOF'
            export EMAIL_USER="${{ secrets.EMAIL_USER }}"
            export EMAIL_PASS="${{ secrets.EMAIL_PASS }}"
            export ALERT_RECIPIENT="${{ secrets.ALERT_RECIPIENT }}"

            cd ~/uptime-arena
            git pull origin main

            cd server
            source venv/bin/activate
            pip install -r requirements.txt

            cd ../client
            npm install
            npm run build

            cp -r dist/* ../server/static/

            cd ../server
            pm2 restart uptime || pm2 start app.py --interpreter venv/bin/python --name uptime
          EOF
