name: Periodic Uptime Check

on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r server/requirements.txt

      - name: Run uptime_checker
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          ALERT_RECIPIENT: ${{ secrets.ALERT_RECIPIENT }}
        run: python3 server/uptime_checker.py
